spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      ## 如果后端项目服务器和数据库服务器不在同一台主机，则需要修改localhost为数据库服务器ip地址
      url: jdbc:mysql://localhost:3306/fmmall?characterEncoding=utf-8
      username: root
      password: root
#mybatis:
#  mapper-locations: classpath:mappers/*Mapper.xml
#  type-aliases-package: com.qfedu.fmmall.entity
mybatis-plus:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.qfedu.fmmall.entity

logging:
  level:
    io.swagger.models.parameters.AbstractSerializableParameter: error
